#!/usr/bin/env node
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { DatabaseSync } from "node:sqlite";
import http from "node:http";
import { pathToFileURL } from "node:url";

const execFileAsync = promisify(execFile);
const HOME = os.homedir();
const APP_DIR = path.join(HOME, "Library", "Application Support", "CodexUsageMonitor");
const CONFIG_DIR = path.join(HOME, ".config", "codex-usage-monitor");
const CONFIG_PATH = path.join(CONFIG_DIR, "config.json");
const DB_PATH = path.join(APP_DIR, "usage.sqlite");
const CODEX_ROOT = path.join(HOME, ".codex");
const DEFAULT_CONFIG = { config_version: 1, port: 47931, scan_interval_seconds: 30, notifications: true, codex: { plan: "personal", five_hour_alert_percent: 10, weekly_alert_percent: 10, rearm_percent: 15, cli_path: "codex", rate_limit_snapshot_path: "", manual_remaining_percent: null } };

function mergeConfig(base, override) { return { ...base, ...override, codex: { ...base.codex, ...(override?.codex || {}) } }; }
function ensureConfig() { fs.mkdirSync(CONFIG_DIR, { recursive: true }); if (!fs.existsSync(CONFIG_PATH)) fs.writeFileSync(CONFIG_PATH, JSON.stringify(DEFAULT_CONFIG, null, 2) + "\n", { mode: 0o600 }); return mergeConfig(DEFAULT_CONFIG, JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"))); }
function writeConfig(config) { fs.mkdirSync(CONFIG_DIR, { recursive: true }); fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2) + "\n", { mode: 0o600 }); }
function editableConfig(config) { return { fiveHourAlertPercent: Number(config.codex.five_hour_alert_percent), weeklyAlertPercent: Number(config.codex.weekly_alert_percent) }; }
function finitePercent(value) { const n = Number(value); return Number.isFinite(n) && n >= 0 && n <= 100 ? n : null; }
function updateEditableConfig(config, input) { const next = mergeConfig(config, {}), fiveHour = finitePercent(input?.fiveHourAlertPercent), weekly = finitePercent(input?.weeklyAlertPercent); if (fiveHour !== null) next.codex.five_hour_alert_percent = fiveHour; if (weekly !== null) next.codex.weekly_alert_percent = weekly; return next; }
function ensureDb() { fs.mkdirSync(APP_DIR, { recursive: true }); const db = new DatabaseSync(DB_PATH); db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS quota_snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,window_name TEXT NOT NULL,remaining_percent REAL,reset_at TEXT,source TEXT NOT NULL,captured_at TEXT NOT NULL,payload_json TEXT); CREATE INDEX IF NOT EXISTS quota_snapshots_window ON quota_snapshots(window_name,captured_at); CREATE TABLE IF NOT EXISTS alert_deliveries(alert_key TEXT PRIMARY KEY,kind TEXT NOT NULL,period_key TEXT NOT NULL,threshold REAL,message TEXT NOT NULL,delivered_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS app_metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);`); return db; }
function findFiles(root, predicate) { const files = []; if (!fs.existsSync(root)) return files; const stack = [root]; while (stack.length) { const current = stack.pop(); let entries; try { entries = fs.readdirSync(current, { withFileTypes: true }); } catch { continue; } for (const entry of entries) { const full = path.join(current, entry.name); if (entry.isDirectory()) stack.push(full); else if (predicate(full)) files.push(full); } } return files; }
function findValue(value, keys, depth = 0) { if (!value || typeof value !== "object" || depth > 8) return undefined; for (const key of keys) if (value[key] !== undefined && value[key] !== null) return value[key]; for (const child of Object.values(value)) { const found = findValue(child, keys, depth + 1); if (found !== undefined) return found; } return undefined; }
function parseTime(value) { if (typeof value === "number") return new Date(value < 10_000_000_000 ? value * 1000 : value).toISOString(); const parsed = value ? new Date(value) : new Date(); return Number.isNaN(parsed.getTime()) ? new Date().toISOString() : parsed.toISOString(); }
function nestedNumber(value, keys, depth = 0) { if (!value || typeof value !== "object" || depth > 8) return undefined; for (const key of keys) if (value[key] !== undefined && Number.isFinite(Number(value[key]))) return Number(value[key]); for (const child of Object.values(value)) { const found = nestedNumber(child, keys, depth + 1); if (found !== undefined) return found; } return undefined; }
function normaliseQuotaWindow(payload, allowAnyWindow = false) { const remaining = nestedNumber(payload, ["remaining_percent", "remainingPercent", "remaining_percentage"]), used = nestedNumber(payload, ["used_percent", "usedPercent"]), minutes = nestedNumber(payload, ["window_minutes", "windowMinutes", "window_duration_mins", "windowDurationMins"]), resetAt = findValue(payload, ["reset_at", "resetAt", "resets_at", "resetsAt"]); return { remaining: remaining ?? (used !== undefined && (allowAnyWindow || minutes === undefined || minutes === 300) ? 100 - used : undefined), resetAt: resetAt ? parseTime(resetAt) : null }; }
function extractCodexRateLimits(root) { const limits = findValue(root, ["rate_limits", "rateLimits"]); if (!limits || typeof limits !== "object") return []; return [["5h", limits.primary || limits.Primary], ["weekly", limits.secondary || limits.Secondary]].map(([windowName, payload]) => { if (!payload || typeof payload !== "object") return null; const quota = normaliseQuotaWindow(payload, windowName === "weekly"); return Number.isFinite(quota.remaining) ? { windowName, remaining: Math.max(0, Math.min(100, quota.remaining)), resetAt: quota.resetAt, payload } : null; }).filter(Boolean); }
function normaliseQuotaWindows(payload) { if (Array.isArray(payload?.windows)) return payload.windows.map((window) => { const name = String(window?.name || window?.window || "").toLowerCase(), windowName = /week|7d|168h/.test(name) ? "weekly" : (/5h|5 hour|five[_ -]?hour/.test(name) ? "5h" : null); if (!windowName) return null; const quota = normaliseQuotaWindow(window, windowName === "weekly"); return Number.isFinite(quota.remaining) ? { windowName, remaining: Math.max(0, Math.min(100, quota.remaining)), resetAt: quota.resetAt, payload: window } : null; }).filter(Boolean); const named = [["5h", payload?.five_hour || payload?.fiveHour || payload?.["5h"]], ["weekly", payload?.weekly || payload?.week || payload?.seven_day || payload?.sevenDay || payload?.["7d"]]].map(([windowName, window]) => { if (!window || typeof window !== "object") return null; const quota = normaliseQuotaWindow(window, windowName === "weekly"); return Number.isFinite(quota.remaining) ? { windowName, remaining: Math.max(0, Math.min(100, quota.remaining)), resetAt: quota.resetAt, payload: window } : null; }).filter(Boolean); return named.length ? named : extractCodexRateLimits(payload); }
function normaliseQuota(payload) { const quota = normaliseQuotaWindows(payload).find((item) => item.windowName === "5h"); return quota ? { remaining: quota.remaining, resetAt: quota.resetAt } : { remaining: undefined, resetAt: null }; }
function latestQuota(db, windowName) { return db.prepare("SELECT remaining_percent,reset_at,source,captured_at FROM quota_snapshots WHERE window_name=? ORDER BY captured_at DESC LIMIT 1").get(windowName) || null; }
function previousQuotaWithDifferentReset(db, windowName, resetAt, source) { return db.prepare("SELECT remaining_percent,reset_at,source,captured_at FROM quota_snapshots WHERE window_name=? AND source=? AND reset_at IS NOT ? ORDER BY captured_at DESC LIMIT 1").get(windowName, source, resetAt) || null; }
function insertQuota(db, windowName, remaining, resetAt, source, payload) { if (!Number.isFinite(remaining)) return; const bounded = Math.max(0, Math.min(100, remaining)), previous = latestQuota(db, windowName); if (previous && Number(previous.remaining_percent) === bounded && previous.reset_at === resetAt && previous.source === source) return; db.prepare("INSERT INTO quota_snapshots(window_name,remaining_percent,reset_at,source,captured_at,payload_json) VALUES (?,?,?,?,?,?)").run(windowName, bounded, resetAt, source, new Date().toISOString(), JSON.stringify(payload)); }
function refreshTranscriptQuota(db) { const files = findFiles(CODEX_ROOT, (file) => file.endsWith(".jsonl") && (file.includes("sessions") || file.includes("archived_sessions"))); const newest = files.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs)[0]; if (!newest) return false; try { const lines = fs.readFileSync(newest).subarray(-256 * 1024).toString("utf8").split("\n"), latest = new Map(); for (const line of lines) try { for (const quota of extractCodexRateLimits(JSON.parse(line))) latest.set(quota.windowName, quota); } catch {} for (const quota of latest.values()) insertQuota(db, quota.windowName, quota.remaining, quota.resetAt, "codex-transcript", quota.payload); return latest.size > 0; } catch { return false; } }
function appServerRequest(cliPath) { return new Promise((resolve, reject) => { const child = spawn(cliPath || "codex", ["app-server", "--listen", "stdio://"], { stdio: ["pipe", "pipe", "ignore"] }); let data = "", initialized = false, settled = false; const finish = (error, value) => { if (settled) return; settled = true; clearTimeout(timer); child.kill("SIGTERM"); error ? reject(error) : resolve(value); }; const timer = setTimeout(() => finish(new Error("app-server timeout")), 8000), send = (message) => child.stdin.write(`${JSON.stringify(message)}\n`); child.on("error", (error) => finish(error)); child.on("close", () => { if (!settled) finish(new Error("app-server closed")); }); child.stdout.on("data", (chunk) => { data += chunk; const lines = data.split(/\r?\n/); data = lines.pop() || ""; for (const line of lines) try { const message = JSON.parse(line); if (message.id === 1 && !initialized) { initialized = true; send({ jsonrpc: "2.0", method: "initialized", params: {} }); send({ jsonrpc: "2.0", id: 2, method: "account/rateLimits/read", params: {} }); } else if (message.id === 2) finish(message.error ? new Error(message.error.message || "app-server error") : null, message.result || message); } catch {} }); send({ jsonrpc: "2.0", id: 1, method: "initialize", params: { clientInfo: { name: "codex-usage-monitor", title: "Codex Usage Monitor", version: "0.1.0" }, capabilities: { experimentalApi: true } } }); }); }
async function refreshQuota(db, config) { try { const quotas = extractCodexRateLimits(await appServerRequest(config.codex.cli_path)); if (quotas.length) { for (const quota of quotas) insertQuota(db, quota.windowName, quota.remaining, quota.resetAt, "codex-app-server", quota.payload); return; } } catch {} if (config.codex.rate_limit_snapshot_path) try { const quotas = normaliseQuotaWindows(JSON.parse(fs.readFileSync(config.codex.rate_limit_snapshot_path, "utf8"))); if (quotas.length) { for (const quota of quotas) insertQuota(db, quota.windowName, quota.remaining, quota.resetAt, "snapshot-file", quota.payload); return; } } catch {} if (refreshTranscriptQuota(db)) return; if (Number.isFinite(Number(config.codex.manual_remaining_percent))) insertQuota(db, "5h", Number(config.codex.manual_remaining_percent), null, "manual", {}); }
function quotaSnapshot(db, windowName) { const quota = latestQuota(db, windowName); return quota ? { remainingPercent: Number(quota.remaining_percent), resetAt: quota.reset_at, source: quota.source, capturedAt: quota.captured_at } : { remainingPercent: null, resetAt: null, source: "unavailable", capturedAt: null }; }
function currentSnapshot(db, config) { return { generatedAt: new Date().toISOString(), codex: { quota5h: quotaSnapshot(db, "5h"), quotaWeekly: quotaSnapshot(db, "weekly"), plan: config.codex.plan || "personal" } }; }
function metadataValue(db, key) { return db.prepare("SELECT value FROM app_metadata WHERE key=?").get(key)?.value || null; }
function setMetadataValue(db, key, value) { db.prepare("INSERT INTO app_metadata(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(key, String(value)); }
async function notify(config, text) { if (!config.notifications) return; if (process.platform !== "darwin") return console.log(`[notification] ${text}`); try { await execFileAsync("/usr/bin/osascript", ["-e", `display notification ${JSON.stringify(text)} with title "Codex Usage Monitor"`]); } catch {} }
async function alertOnQuota(db, config, windowName, quota, threshold) { const remaining = quota.remainingPercent; if (!Number.isFinite(remaining)) return; const stateKey = `alert-state:${windowName}:${threshold}`; if (remaining > Math.max(Number(config.codex.rearm_percent) || 0, threshold)) return setMetadataValue(db, stateKey, "armed"); if (remaining > threshold || metadataValue(db, stateKey) === "triggered") return; const message = `Codex has ${remaining.toFixed(1)}% of its ${windowName === "5h" ? "5-hour" : "weekly"} quota remaining.`; db.prepare("INSERT OR IGNORE INTO alert_deliveries(alert_key,kind,period_key,threshold,message,delivered_at) VALUES (?,?,?,?,?,?)").run(`${windowName}:${threshold}:${new Date().toISOString()}`, "quota", windowName, threshold, message, new Date().toISOString()); await notify(config, message); setMetadataValue(db, stateKey, "triggered"); }
async function refresh(db, config) { await refreshQuota(db, config); const snapshot = currentSnapshot(db, config); await alertOnQuota(db, config, "5h", snapshot.codex.quota5h, config.codex.five_hour_alert_percent); await alertOnQuota(db, config, "weekly", snapshot.codex.quotaWeekly, config.codex.weekly_alert_percent); return snapshot; }
function json(res, status, value) { res.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }); res.end(JSON.stringify(value)); }
function requestBody(req) { return new Promise((resolve, reject) => { let body = ""; req.setEncoding("utf8"); req.on("data", (chunk) => { body += chunk; if (body.length > 32_000) req.destroy(); }); req.on("end", () => resolve(body)); req.on("error", reject); }); }
function startServer(db, config) { const server = http.createServer(async (req, res) => { const url = new URL(req.url, `http://127.0.0.1:${config.port}`); if (req.method === "GET" && url.pathname === "/health") return json(res, 200, { ok: true, version: "0.1.0" }); if (req.method === "GET" && url.pathname === "/config") return json(res, 200, editableConfig(config)); if (req.method === "GET" && url.pathname === "/snapshot") return json(res, 200, currentSnapshot(db, config)); if (req.method === "GET" && url.pathname === "/alerts") return json(res, 200, db.prepare("SELECT * FROM alert_deliveries ORDER BY delivered_at DESC LIMIT 50").all()); if (req.method === "POST" && url.pathname === "/config") try { Object.assign(config, updateEditableConfig(config, JSON.parse(await requestBody(req) || "{}"))); writeConfig(config); return json(res, 200, editableConfig(config)); } catch (error) { return json(res, 400, { error: "invalid_config", message: error.message }); } if (req.method === "POST" && url.pathname === "/refresh") return json(res, 200, await refresh(db, config)); return json(res, 404, { error: "not_found" }); }); server.listen(config.port, "127.0.0.1"); }
async function main() { const config = ensureConfig(), db = ensureDb(); if (process.argv.includes("--snapshot")) { console.log(JSON.stringify(await refresh(db, config), null, 2)); db.close(); return; } await refresh(db, config); startServer(db, config); const interval = setInterval(() => refresh(db, config).catch(console.error), Math.max(15, config.scan_interval_seconds) * 1000); const stop = () => { clearInterval(interval); db.close(); process.exit(0); }; process.on("SIGINT", stop); process.on("SIGTERM", stop); console.log(`Codex Usage Monitor listening on http://127.0.0.1:${config.port}`); }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main().catch((error) => { console.error(error); process.exit(1); });
export { DEFAULT_CONFIG, editableConfig, normaliseQuota, normaliseQuotaWindows, previousQuotaWithDifferentReset, updateEditableConfig };
